name: meu_qr_code
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobile_scanner: ^2.0.0
  flutter_share: ^2.0.0
  url_launcher: ^6.1.4
  google_mobile_ads: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app/qr-code.png"
  adaptive_icon_background: "#FFFFFF"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/website.png
